Name = "EdgeDNS"
Description = ''''''
URL = "https://www.akamai.com/us/en/products/security/edge-dns.jsp"
Code = "edgedns"
Since = "v3.8.0"

Example = ''''''

[Configuration]
  [Configuration.Credentials]
    AKAMAI_HOST = "API host"
    AKAMAI_CLIENT_TOKEN = "Client token"
    AKAMAI_CLIENT_SECRET = "Client secret"
    AKAMAI_ACCESS_TOKEN = "Access token"
  [Configuration.Additional]
    AKAMAI_POLLING_INTERVAL = "Time between DNS propagation check"
    AKAMAI_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    AKAMAI_TTL = "The TTL of the TXT record used for the DNS challenge"

[Links]
  API = "https://developer.akamai.com/api/cloud_security/edge_dns_zone_management/v2.html"
  GoClient = "https://github.com/akamai/AkamaiOPEN-edgegrid-golang"


